// Code generated by protoc-gen-go.
// source: TestMessage.proto
// DO NOT EDIT!

/*
Package PbTest is a generated protocol buffer package.

It is generated from these files:
	TestMessage.proto

It has these top-level messages:
	TestMessage
*/
package PbTest

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TestMessage_TType int32

const (
	TestMessage_CREATE TestMessage_TType = 0
	TestMessage_UPDATE TestMessage_TType = 1
	TestMessage_DELETE TestMessage_TType = 2
)

var TestMessage_TType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
}
var TestMessage_TType_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x TestMessage_TType) Enum() *TestMessage_TType {
	p := new(TestMessage_TType)
	*p = x
	return p
}
func (x TestMessage_TType) String() string {
	return proto.EnumName(TestMessage_TType_name, int32(x))
}
func (x *TestMessage_TType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestMessage_TType_value, data, "TestMessage_TType")
	if err != nil {
		return err
	}
	*x = TestMessage_TType(value)
	return nil
}

type TestMessage struct {
	ClientName       *string                `protobuf:"bytes,1,req,name=clientName" json:"clientName,omitempty"`
	ClientId         *int32                 `protobuf:"varint,2,req,name=clientId" json:"clientId,omitempty"`
	Description      *string                `protobuf:"bytes,3,opt,name=description,def=NONE" json:"description,omitempty"`
	MessageItems     []*TestMessage_MsgItem `protobuf:"bytes,4,rep,name=messageItems" json:"messageItems,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}

const Default_TestMessage_Description string = "NONE"

func (m *TestMessage) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *TestMessage) GetClientId() int32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *TestMessage) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return Default_TestMessage_Description
}

func (m *TestMessage) GetMessageItems() []*TestMessage_MsgItem {
	if m != nil {
		return m.MessageItems
	}
	return nil
}

type TestMessage_MsgItem struct {
	Id               *int32             `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ItemName         *string            `protobuf:"bytes,2,opt,name=itemName" json:"itemName,omitempty"`
	ItemValue        *int32             `protobuf:"varint,3,opt,name=itemValue" json:"itemValue,omitempty"`
	TransactionType  *TestMessage_TType `protobuf:"varint,4,opt,name=transaction_type,enum=PbTest.TestMessage_TType" json:"transaction_type,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *TestMessage_MsgItem) Reset()         { *m = TestMessage_MsgItem{} }
func (m *TestMessage_MsgItem) String() string { return proto.CompactTextString(m) }
func (*TestMessage_MsgItem) ProtoMessage()    {}

func (m *TestMessage_MsgItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TestMessage_MsgItem) GetItemName() string {
	if m != nil && m.ItemName != nil {
		return *m.ItemName
	}
	return ""
}

func (m *TestMessage_MsgItem) GetItemValue() int32 {
	if m != nil && m.ItemValue != nil {
		return *m.ItemValue
	}
	return 0
}

func (m *TestMessage_MsgItem) GetTransactionType() TestMessage_TType {
	if m != nil && m.TransactionType != nil {
		return *m.TransactionType
	}
	return TestMessage_CREATE
}

func init() {
	proto.RegisterEnum("PbTest.TestMessage_TType", TestMessage_TType_name, TestMessage_TType_value)
}
